# Generated by Django 6.0.3 on 2026-03-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_folder', models.CharField(blank=True, default='', max_length=1000)),
                ('output_folder', models.CharField(blank=True, default='', max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=1200, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Unread'), (1, 'Favorite'), (2, 'Disliked')], default=0)),
                ('exists_on_disk', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['filename', 'id'],
            },
        ),
    ]
