# Generated by Django 6.0.3 on 2026-03-18 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoitem',
            name='state_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
