# Generated by Django 6.0.3 on 2026-03-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0002_photoitem_state_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoitem',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
